# Generated by Django 5.0.1 on 2024-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_type_alter_review_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateField(null=True),
        ),
    ]
